apiVersion: apps/v1
kind: Deployment
metadata:
  name: photographia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photographia  
  template:
    metadata:
      labels:
        app: photographia
    spec:
      containers:
        - name: photographia
          image: mosub/pipline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
